name       : geoclue
version    : 2.4.3
release    : 7
source     :
    - https://www.freedesktop.org/software/geoclue/releases/2.4/geoclue-2.4.3.tar.xz : ada9dba870dd79e1b21923aeda4d82b66cbda39e57978fbe3d83d356cc3c605e
license    :
    - GPL-2.0+
summary    : GeoInformation service
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-glib)
    - pkgconfig(avahi-glib)
replaces   :
    - devel : libgeoclue-devel
    - libgeoclue
description: |
    GeoClue is a modular geoinformation service built on top of the D-Bus messaging system. The goal of the GeoClue project is to make creating location-aware applications as simple as possible.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    autoreconf -vfi

    %configure --disable-static --libexecdir=/usr/lib/geoclue
build      : |
    %make
install    : |
    %make_install
