name       : geoclue
version    : 2.4.8
release    : 14
source     :
    - https://www.freedesktop.org/software/geoclue/releases/2.4/geoclue-2.4.8.tar.xz : 12175167a97f30cb9d739225b339a69a2237ebc4c91ccfb6e73059504f0ecf23
license    : GPL-2.0
component  : programming
summary    : GeoInformation service
description: |
    GeoClue is a modular geoinformation service built on top of the D-Bus messaging system. The goal of the GeoClue project is to make creating location-aware applications as simple as possible.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-glib)
replaces   :
    - devel : libgeoclue-devel
    - libgeoclue
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %reconfigure --disable-static --libexecdir=/usr/lib/geoclue
build      : |
    %make
install    : |
    %make_install
