name       : geoclue
version    : 2.4.12
release    : 13
source     :
    - https://www.freedesktop.org/software/geoclue/releases/2.4/geoclue-2.4.12.tar.xz : 05d0e2ec077a685de2a9c63973fe6d18366ca53881d1f0750110b93c5c68caca
license    : GPL-2.0
component  : programming
summary    : GeoInformation service
description: |
    GeoClue is a modular geoinformation service built on top of the D-Bus messaging system. The goal of the GeoClue project is to make creating location-aware applications as simple as possible.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-glib)
replaces   :
    - devel : libgeoclue-devel
    - libgeoclue
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %reconfigure --disable-static --libexecdir=/usr/lib/geoclue
build      : |
    %make
install    : |
    %make_install
