name        : geoclue
version     : 2.1.9
release     : 5
source      :
    - http://www.freedesktop.org/software/geoclue/releases/2.1/geoclue-2.1.9.tar.xz : b416eea6042d774359f7a141e4e57704c3220363ab8e0bf5c212b1bd2976092b
license     :
    - GPL-2.0+
summary     : GeoInformation service
builddeps   :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-glib)
replaces:
    - devel: libgeoclue-devel
    - libgeoclue
description : |
    GeoClue is a modular geoinformation service built on top of the D-Bus messaging system. The goal of the GeoClue project is to make creating location-aware applications as simple as possible.
setup      : |
    %configure --disable-static --libexecdir=/usr/lib/geoclue
build      : |
    %make
install    : |
    %make_install
